### ISSUE TITLE
Facebook reactions (likes / comments) being interpreted as mentions

### ISSUE THREAD

**Issue by alohastone** [acegiak/Semantic-Linkbacks#26]
Hey guys,

I implemented webmentions on my blog several months ago, and started working on the facepile-display with the semantic comments plugin again yesterday.

While doing that, I noticed that somehow all (new) facebook reactions to my posts show up as mentions, although they are in fact likes and / or comments.

I'm using brid.gy to retrieve the reactions, and on the brid.gy site they show up as comments / likes, like they should.

![alohaweblog facebook - bridgy 2015-09-08 15-26-20](https://cloud.githubusercontent.com/assets/3405023/9735900/46cdef58-563e-11e5-8048-36988036f142.jpg)

But in my wordpress dashboard they all show up as mentions instead:

<img width="1097" alt="bildschirmfoto 2015-09-08 um 14 58 53" src="https://cloud.githubusercontent.com/assets/3405023/9735918/5f23ec1a-563e-11e5-9984-7cb6dc370e3e.png">

Here's an example link to a post, in which all mentions should in fact be likes: http://www.alohastone.com/2015/09/02/flo-mega-haut-einen-gegen-rassisten-raus-lamm-vindaloo-download/#comments

And here's one that should show a like and a comment, but instead shows 2 mentions: http://www.alohastone.com/2015/09/04/statik-selektah-beautiful-life-feat-action-bronson-joey-bada/#comments

I don't really know if this is a bug with the semantic linkbacks plugin or if it needs an update, or if brid.gy or facebook changed something. But I'd be thankful for any help on this. And, while I'm here, let me thank you for the work you're putting into this. The more I understand this indieweb stuff, the more I like it :)

**Comment by armingrewe** [comment]
Now that you mention it, I just checked on mine and that's a very recent change (which I hadn't noticed yet). Anything until including 6/Sep is showing correctly, everything from 7/Sep onwards shows as "mentioned" regardless of what it really is.
I don't think I made any changes to my blog setup/plugins, so it's likely a Bridgy change?

**Comment by armingrewe** [comment]
Should have mentioned, this is for everything, not just Facebook. Both Twitter favourites and retweets show as "mentioned" as well.

**Comment by pfefferle** [comment]
Can you please send me the bird.gy URLs?

**Comment by pfefferle** [comment]
OK, this seem to be a bug in Brid.gy (/cc @snarfed)


```HTML
<a class="u-mention" href="https://indiewebcamp.com/2014-review#This_Is_A_Movement"></a>
<a class="u-mention" href="http://notizblog.org/2015/07/25/indiewebcamp-2014-this-is-a-movement/"></a>

<a class="u-like u-like-of" href="https://plus.google.com/+MatthiasPfefferle/posts/9neajHNpoKf"></a>
```

The only link that includes a `u-like` is the link to the Google URL. The Blogpost (http://notizblog.org/...) is linked with `u-mention` that's why it is marked up as a mention.

**Comment by alohastone** [comment]
You're right. Same goes for twitter. Everything seems to show as "mentioned".

@pfefferle you mean the profile URLs? https://www.brid.gy/twitter/alohastone and https://www.brid.gy/facebook/103109124889

**Comment by snarfed** [comment]
hey all! this is likely due to ongoing work in snarfed/bridgy#51. we're tightening up our logic for determining POSSE posts and original post links vs mere mention links. i'll look into this example.

**Comment by snarfed** [comment]
sorry for the breakage, all! i've pushed out a fix for the facebook case, and i'll fix the twitter case soon. thanks for your patience.

**Comment by snarfed** [comment]
ok, twitter should be fixed for now. snarfed/bridgy#51 is still very much in progress, and delicate, so there may be more bumps in the road ahead. apologies in advance. feel free to close this issue and report any new problems there.

**Comment by armingrewe** [comment]
Thanks for the quick reaction, I'll watch out for new mentions/likes/etc coming in the next few days if there are any issues

**Comment by alohastone** [comment]
Thanks for clearing this up guys. I'll keep an eye on this, too. Take your time.

**Comment by snarfed** [comment]
i assume this worked for you all? should we close this issue?

also related, same symptom but maybe different bug: pfefferle/wordpress-semantic-linkbacks#63
